import test from 'node:test';
import assert from 'node:assert/strict';
import {RunView,UI_TEXT_BYTES,UI_RETAINED_ITEMS,requestId,isTerminal,frameSequence} from '../src/index.mjs';
import {message,tool,frame,frames,snapshot,outcome} from './helpers.mjs';

test('text deltas followed by authoritative completion do not double append',()=>{const view=new RunView('r');for(const f of frames())view.apply(f);assert.equal(view.state.items[0].content.text,'hello');assert.equal(view.state.outcome.status,'completed');});
test('duplicate sequence from a reconnect is ignored',()=>{const view=new RunView('r');const f=frames()[0];assert.equal(view.apply(f),true);assert.equal(view.apply(f),false);assert.equal(view.state.seq,1);});
test('a gap requires snapshot recovery rather than guessing missing text',()=>{const view=new RunView('r');view.apply(frames()[0]);assert.throws(()=>view.apply(frames()[2]),e=>e.code==='gap'&&e.cursor===1);view.apply({kind:'snapshot',reason:'source_resync',snapshot:snapshot(5,true)});assert.equal(view.state.seq,5);assert.equal(view.state.outcome.status,'completed');});
test('wrong run and protocol version are rejected',()=>{const view=new RunView('r');assert.throws(()=>view.apply(frame(1,{type:'run/started'},'other')),e=>e.code==='protocol');const f=frames()[0];f.envelope.protocol_version=3;assert.throws(()=>view.apply(f),e=>e.code==='protocol');});
test('older snapshot never regresses the current projection',()=>{const view=new RunView('r');view.apply({kind:'snapshot',reason:'initial',snapshot:snapshot(5,true)});assert.equal(view.apply({kind:'snapshot',reason:'initial',snapshot:snapshot(0)}),false);assert.equal(view.state.seq,5);});
test('partial arguments are only a preview; completed item supplies parsed arguments',()=>{const view=new RunView('r');const item=tool();view.apply(frame(1,{type:'item/started',item}));view.apply(frame(2,{type:'item/toolCall/argumentsDelta',item_id:item.id,call_id:'c1',name:'add',delta:'{"a":'}));assert.equal(view.state.items[0].content.arguments,null);item.state='running';item.content={...item.content,call_id:'c1',name:'add',arguments_text:'{"a":1}',arguments:{a:1}};view.apply(frame(3,{type:'item/updated',item}));assert.deepEqual(view.state.items[0].content.arguments,{a:1});});
test('tool progress and final result remain distinct',()=>{const view=new RunView('r');const item=tool();item.state='running';view.apply(frame(1,{type:'item/started',item}));view.apply(frame(2,{type:'item/toolCall/outputDelta',item_id:item.id,text:'testing\n'}));const final=structuredClone(view.state.items[0]);final.state='completed';final.content.result={call_id:'c',status:'success',content:'all passed',truncated:false,original_bytes:10,artifact:null};final.content.details={'coding.diff':{path:'a.rs',added:2}};view.apply(frame(3,{type:'item/completed',item:final}));assert.equal(view.state.items[0].content.output,'testing\n');assert.equal(view.state.items[0].content.result.content,'all passed');assert.equal(view.state.items[0].content.details['coding.diff'].added,2);});
test('UTF-8 previews are byte bounded without broken characters',()=>{const view=new RunView('r');view.apply(frame(1,{type:'item/started',item:message()}));view.apply(frame(2,{type:'item/agentMessage/delta',item_id:'step-1-message',text:'汉🙂'.repeat(20000)}));const c=view.state.items[0].content;assert.equal(c.truncated,true);assert.ok(new TextEncoder().encode(c.text).length<=UI_TEXT_BYTES);assert.equal(c.text.includes('�'),false);});
test('visible work item retention is bounded and pruning is explicit',()=>{const view=new RunView('r');for(let i=0;i<UI_RETAINED_ITEMS+7;i++){const item=message('x','completed');item.id='m'+i;view.apply(frame(i+1,{type:'item/completed',item}));}assert.equal(view.state.items.length,UI_RETAINED_ITEMS);assert.equal(view.state.pruned_items,7);});
test('unknown event does not advance sequence',()=>{const view=new RunView('r');assert.throws(()=>view.apply(frame(1,{type:'not-a-v2-event'})),e=>e.code==='protocol');assert.equal(view.state.seq,0);});
test('fault and terminal helpers expose a reliable completion boundary',()=>{assert.equal(isTerminal(frames().at(-1)),true);assert.equal(isTerminal({kind:'snapshot',snapshot:snapshot(5,true)}),true);assert.equal(frameSequence(frames()[0]),1);assert.throws(()=>new RunView('r').apply({kind:'fault',error:{code:'internal',message:'stopped'}}),e=>e.code==='internal');});
test('request keys are distinct bounded identifiers',()=>{const a=requestId(),b=requestId();assert.notEqual(a,b);assert.match(a,/^[a-zA-Z0-9_.-]{1,128}$/);});
