[package]
name = "tauri-composition"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[features]
default = []
tauri = ["dep:tauri", "tauri-bridge/tauri"]

[dependencies]
api.workspace = true
runtime.workspace = true
application.workspace = true
tauri-bridge.workspace = true
tauri = { version = "2", default-features = false, optional = true }
