// Production renderer contracts in the formal page; owned browser/fixture only.
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { mkdtemp, mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { startUiServer } from '../../../scripts/dev-web.mjs';
import { createFixtureApiServer, TEST_TOKEN } from './fixture-server.mjs';
const scratch = await mkdtemp(join(tmpdir(),'mona-content-ui-')), profile=join(scratch,'browser'), output=resolve('.tmp-verify/content-ui-browser-report');
await mkdir(output,{recursive:true});
const errors=[], checks=[], requests=[]; let api,ui,browser,socket,sequence=0,origin='';const pending=new Map();
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function wait(fn,label,timeout=20000){const end=Date.now()+timeout;while(Date.now()<end){if(await fn())return;await sleep(50);}throw Error('Timeout: '+label);}
function check(name,condition){assert.ok(condition,name);checks.push(name);console.log('PASS '+name);}
function send(method,params={}){return new Promise((resolve,reject)=>{const id=++sequence,timer=setTimeout(()=>{pending.delete(id);reject(Error('CDP timeout '+method));},25000);pending.set(id,{resolve,reject,timer});socket.send(JSON.stringify({id,method,params}));});}
async function evaluate(expression){const value=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(value.exceptionDetails)throw Error(value.exceptionDetails.exception?.description||'JS failure');return value.result.value;}
const pageWait=(expression,label,time)=>wait(()=>evaluate(expression),label,time);
async function screenshot(name){const image=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(join(output,name+'.png'),Buffer.from(image.data,'base64'));}
try{
  api=createFixtureApiServer({allowOrigin:value=>value===origin,management:true});await new Promise(r=>api.listen(0,'127.0.0.1',r));
  ui=await startUiServer({host:'127.0.0.1',port:0,endpoint:`http://127.0.0.1:${api.address().port}`,token:TEST_TOKEN});origin=`http://127.0.0.1:${ui.address().port}`;
  browser=spawn(process.env.BROWSER_BIN||(process.platform==='win32'?'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe':'chromium'),['--headless=new','--disable-gpu','--no-first-run','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{stdio:'ignore'});
  let port;await wait(async()=>{try{port=Number((await readFile(join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0]);return port>0;}catch{return false;}},'browser');
  const pages=await(await fetch(`http://127.0.0.1:${port}/json/list`)).json();socket=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);await once(socket,'open');
  socket.addEventListener('message',event=>{const message=JSON.parse(event.data),request=pending.get(message.id);if(request){pending.delete(message.id);clearTimeout(request.timer);message.error?request.reject(Error(JSON.stringify(message.error))):request.resolve(message.result);}if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails.exception?.description||'JS exception');if(message.method==='Network.requestWillBeSent')requests.push(message.params.request.url);});
  await send('Page.enable');await send('Runtime.enable');await send('Network.enable');await send('Emulation.setFocusEmulationEnabled',{enabled:true});await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
  await send('Page.navigate',{url:origin});await pageWait("document.querySelector('#model-label')?.textContent==='fixture-chat'",'formal app ready');
  await evaluate("(async()=>{window.renderer=await import('/apps/web/content-renderer.mjs');document.querySelector('#welcome').hidden=true;window.host=document.createElement('div');host.className='message-text';document.querySelector('#timeline').replaceChildren(host);})()");
  const source='foo_bar_baz\n\n| Name |\n| --- |\n| A\\|B |\n\n**粗体 *嵌套* 正常**\n\n- [x] 已完成\n- [ ] 待办\n\n$x_i^2$\n\n\\(\\frac{a}{b}\\)\n\n<script>window.__unsafe=true</script>\n\n![remote](https://example.invalid/tracker.png)\n\n[bad](javascript:alert(1))\n\n[local](docs/report.md)';
  await evaluate(`renderer.renderMessage(host,${JSON.stringify(source)},{openFile:path=>{window.__opened=path;},contextKey:'s-one'})`);
  check('Markdown keeps intraword underscores and nested emphasis correct',await evaluate("host.firstElementChild.textContent==='foo_bar_baz' && host.querySelector('strong em').textContent==='嵌套'"));
  check('single-column tables and escaped pipes render actual cells',await evaluate("host.querySelectorAll('table').length===1 && host.querySelector('td').textContent==='A|B'"));
  check('task lists render disabled semantic checkboxes',await evaluate("host.querySelectorAll('.message-task-checkbox').length===2 && host.querySelector('input:checked').disabled"));
  check('KaTeX preserves x sub i superscript 2 as a combined script',await evaluate("host.querySelector('math msubsup')?.textContent==='xi2' && host.querySelectorAll('math').length===2"));
  check('raw HTML and executable URI never execute or become links',await evaluate("!window.__unsafe && !host.querySelector('script') && !host.querySelector('a[href^=javascript]') && host.textContent.includes('<script>')"));
  check('remote Markdown image is real media UI but does not fetch without consent',await evaluate("host.querySelector('.message-media img') && !host.querySelector('.message-media img').hasAttribute('src')")&&!requests.some(url=>url.includes('example.invalid')));
  await evaluate("host.querySelector('.message-file-link').click()");check('local links use an explicit presentation callback, never raw file URLs',await evaluate("window.__opened==='docs/report.md'"));
  check('workspace file links use the ZCode inline icon treatment',await evaluate("host.querySelector('.message-file-link .line-icon')?.getBoundingClientRect().width===16"));
  check('table copy, download and large preview actions are installed',await evaluate("['复制表格','下载 CSV','放大表格'].every(label=>host.querySelector(`.message-table-actions button[aria-label=\"${label}\"]`))"));
  await evaluate("host.querySelector('.message-table-actions button[aria-label=\"放大表格\"]').click()");check('table preview opens as an accessible modal',await evaluate("document.querySelector('dialog[open] table td').textContent==='A|B' && document.querySelector('dialog[open]').hasAttribute('aria-labelledby')"));
  check('table preview retains ZCode row separators and sticky heading',await evaluate("getComputedStyle(document.querySelector('dialog[open] th')).position==='sticky'&&getComputedStyle(document.querySelector('dialog[open] td')).borderLeftWidth==='0px'"));await evaluate("document.querySelector('dialog[open]').close()");
  const wideHeaders=Array.from({length:8},(_,i)=>`列 ${i+1}`),wideValues=Array.from({length:8},(_,i)=>`这是较长的单元格内容 ${i+1}`);
  await evaluate(`renderer.renderMessage(host,${JSON.stringify(`| ${wideHeaders.join(' | ')} |\n| ${wideHeaders.map(()=> '---').join(' | ')} |\n| ${wideValues.join(' | ')} |`)},{contextKey:'wide-table'})`);
  await pageWait("host.querySelector('.message-table-frame.has-right-edge')&&!host.querySelector('.message-table-wide').hidden",'wide table scroll affordance');
  await evaluate("window.wideTable=host.querySelector('.message-table-frame');window.originalTableWidth=wideTable.getBoundingClientRect().width;wideTable.querySelector('.message-table-wide').click()");
  check('wide tables expose the ZCode-style expanded horizontal reading mode',await evaluate("wideTable.classList.contains('is-expanded')&&wideTable.getBoundingClientRect().width>originalTableWidth"));
  await screenshot('zcode-wide-table');
  await evaluate("wideTable.querySelector('.message-table').scrollLeft=100000");
  await pageWait("wideTable.classList.contains('has-left-edge')",'table left overflow hint');
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:900,deviceScaleFactor:1,mobile:false});await sleep(120);
  check('expanded wide table remains scoped to the mobile conversation',await evaluate("document.documentElement.scrollWidth<=390&&wideTable.querySelector('.message-table').scrollWidth>wideTable.querySelector('.message-table').clientWidth"));
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
  const pixel='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
  await evaluate(`renderer.renderMessage(host,${JSON.stringify(`![一](${pixel})\n\n![二](${pixel})`)},{contextKey:'gallery'})`);
  await pageWait("host.querySelectorAll('.message-image-gallery .message-image-trigger[data-state=ready]').length===2",'grouped image thumbnails');
  check('consecutive images use ZCode-size focusable thumbnails and a preview',await evaluate("(()=>{const gallery=host.querySelector('.message-image-gallery'),items=[...gallery.querySelectorAll('.message-image-trigger')];return items.length===2&&items.every(item=>item.getBoundingClientRect().height===176&&item.getAttribute('aria-disabled')==='false')})()"));
  await screenshot('zcode-image-gallery');
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:900,deviceScaleFactor:1,mobile:false});await sleep(120);
  check('image gallery stacks into full-width mobile thumbnails',await evaluate("(()=>{const gallery=host.querySelector('.message-image-gallery'),items=[...gallery.querySelectorAll('.message-image-trigger')];return items.every(item=>item.getBoundingClientRect().height===128&&Math.abs(item.getBoundingClientRect().width-gallery.getBoundingClientRect().width)<2)&&document.documentElement.scrollWidth<=390})()"));
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
  await evaluate("host.querySelector('.image-preview-open').click()");check('image thumbnail opens the ZCode-shaped preview with gallery navigation',await evaluate("document.querySelector('dialog[open].image-preview-dialog img')?.alt==='一'&&document.querySelector('dialog[open] .content-preview-header button[aria-label=\"关闭图片\"]')&&!document.querySelector('dialog[open] .content-preview-header button[aria-label=\"下载图片\"]').hidden&&document.querySelectorAll('dialog[open] .message-image-gallery-nav button').length===2&&document.querySelector('dialog[open] .content-zoom-reading')?.textContent==='100%'"));
  await screenshot('zcode-image-preview');
  await evaluate("document.querySelector('dialog[open] button[aria-label=\"放大图片\"]').click()");check('image preview zoom uses ZCode step controls',await evaluate("document.querySelector('dialog[open] .content-zoom-reading')?.textContent==='150%'&&document.querySelector('dialog[open] .content-zoom-area')?.dataset.zoom==='150'"));
  await evaluate("document.querySelector('dialog[open] .message-image-gallery-nav button:last-child').click()");check('gallery navigation selects the next image',await evaluate("document.querySelector('dialog[open] .content-zoom-area img')?.alt==='二'"));
  await evaluate("document.querySelector('dialog[open]').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}))");check('keyboard navigation returns to the previous image',await evaluate("document.querySelector('dialog[open] .content-zoom-area img')?.alt==='一'"));await evaluate("document.querySelector('dialog[open]').close()");
  await evaluate("renderer.renderMessage(host,'```text\\n![一](a.png)\\n\\n![二](b.png)\\n```',{contextKey:'image-fence'})");
  check('image grouping never rewrites a code fence',await evaluate("!host.querySelector('.message-image-gallery')&&host.querySelector('.message-code code').textContent.includes('a.png)\\n\\n![二]')"));
  await evaluate("renderer.renderMessage(host,'> 第一段\\n>\\n> 第二段\\n\\n---\\n\\n~~已撤销~~ 脚注[^1]\\n\\n[^1]: 来源说明',{contextKey:'markdown-misc'})");
  check('quote, rule, strikethrough and footnote remain readable',await evaluate("host.querySelectorAll('blockquote p').length===2&&getComputedStyle(host.querySelector('blockquote')).borderLeftWidth==='2px'&&host.querySelector('hr')&&host.querySelector('del').textContent==='已撤销'&&host.querySelector('.message-footnotes li').textContent.includes('来源说明')"));
  const code='fn main() {\n'+Array.from({length:24},(_,i)=>`    let value_${i} = ${i};`).join('\n')+'\n}';
  const answer='# 标题\n\n第一段稳定正文\n\n```rust\n'+code+'\n```\n\n尾段';
  await evaluate(`renderer.renderMessage(host,${JSON.stringify(answer)},{streaming:true,contextKey:'stream'})`);
  await evaluate("host.querySelector('.code-expand').click();window.__code=host.querySelector('.message-code-block');window.__heading=host.querySelector('h1');const r=document.createRange();r.selectNodeContents(host.querySelector('p'));getSelection().removeAllRanges();getSelection().addRange(r)");
  await evaluate(`renderer.renderMessage(host,${JSON.stringify(answer+'继续输出')},{streaming:true,contextKey:'stream'})`);
  check('streaming preserves expanded code, stable block identity and selection',await evaluate("__code===host.querySelector('.message-code-block') && !__code.classList.contains('is-collapsed') && __heading===host.querySelector('h1') && getSelection().toString()==='第一段稳定正文'"));
  await evaluate("getSelection().removeAllRanges()");await evaluate(`renderer.renderMessage(host,${JSON.stringify(answer+'完成')},{streaming:false,contextKey:'stream'})`);await pageWait("host.querySelector('.hljs-keyword')",'real highlighter');
  check('language-aware highlighting is deferred until completion without resetting user expansion',await evaluate("!__code.classList.contains('is-collapsed') && host.querySelector('.hljs-keyword').textContent==='fn'"));
  await evaluate("host.querySelector('.code-wrap').click()");check('code wrap is a stable user-controlled mode',await evaluate("__code.classList.contains('is-wrapped') && host.querySelector('.code-wrap').getAttribute('aria-pressed')==='true'"));
  await evaluate("renderer.renderMessage(host,'> ```rust\\n> fn nested() {}\\n> ```',{contextKey:'nested',streaming:true})");
  await evaluate("renderer.renderMessage(host,'> ```rust\\n> fn nested() {}\\n> ```',{contextKey:'nested',streaming:false})");
  await pageWait("host.querySelector('blockquote .hljs-keyword')",'nested code completes');
  check('nested fenced code receives completed-state highlighting',true);
  const diagrams='```mermaid\nsequenceDiagram\n Alice->>Bob: Hello\n Bob-->>Alice: World\n```\n\n```mermaid\nflowchart LR\n subgraph Group\n A[Start] --> B{Check}\n end\n B --> C[Done]\n```';
  await evaluate(`renderer.renderMessage(host,${JSON.stringify(diagrams)},{contextKey:'diagrams'})`);
  await pageWait("host.querySelectorAll('img.message-mermaid').length===2 && [...host.querySelectorAll('img.message-mermaid')].every(img=>img.naturalWidth>0)",'actual Mermaid sequence/subgraph',40000);
  check('real Mermaid renders sequence diagrams and flowchart subgraphs, not a hand-drawn subset',true);
  check('Mermaid computation is isolated from application origin and network',await evaluate("document.querySelector('.mona-diagram-engine').getAttribute('sandbox')==='allow-scripts'"));await screenshot('diagrams-light');
  await evaluate("host.querySelector('img.message-mermaid').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}))");check('diagram double-click opens the rendered preview with zoom controls',await evaluate("document.querySelector('dialog[open] img').naturalWidth>0 && document.querySelectorAll('dialog[open] .content-preview-controls button').length===4"));await evaluate("document.querySelector('dialog[open]').close()");
  await evaluate("renderer.renderMessage(host,'```mermaid\\nsequenceDiagram\\nthis is invalid syntax !\\n```',{contextKey:'bad-diagram'})");await pageWait("host.textContent.includes('源码已保留')",'invalid diagram fallback',30000);check('invalid diagrams preserve complete source with a retry action',await evaluate("host.querySelector('pre').textContent.includes('this is invalid')"));
  await evaluate("renderer.renderMessage(host,('段落内容。'.repeat(120)+'\\n\\n').repeat(70),{contextKey:'large'})");
  check('large Markdown parses outside the main thread and retains the complete body',await evaluate("host.querySelectorAll('p').length===70 && !host.querySelector('.message-raw-fallback')"));
  await evaluate("renderer.renderMessage(host,'X'.repeat(1048577),{contextKey:'too-big'})");check('oversized content is not dropped and safely falls back to its original text',await evaluate("host.querySelector('.message-raw-fallback').textContent.length===1048577"));
  await evaluate("(async()=>{const {TurnView}=await import('/apps/web/run-view.mjs');renderer.disposeMessage(host);window.turn=new TurnView('用户原文',{contextKey:'tools'});document.querySelector('#timeline').replaceChildren(turn.turn);window.snap={run_id:'r',items:[{id:'t',step:1,state:'running',content:{kind:'tool_call',name:'shell',arguments:{command:'echo hello'},output:'hello\\n',details:{test:{value:1}}}}],outcome:null};turn.update(snap);turn.entries.get('t').node.open=true;})()");
  await pageWait("document.querySelector('.activity-panel-output')",'lazy tool panel');
  await evaluate("window.__log=document.querySelector('.activity-panel-output');window.__json=document.querySelector('.structured-json');__json.open=true;snap.items[0].content.output+='second\\n';turn.update(snap)");
  check('tool stream appends to the existing log and keeps JSON detail expansion',await evaluate("__log===document.querySelector('.activity-panel-output') && __json===document.querySelector('.structured-json') && __json.open && __log.textContent.includes('second')"));
  check('expanded command and output use ZCode-sized terminal presentation',await evaluate("(()=>{const panel=__log.closest('.activity-panel'),style=node=>getComputedStyle(node);return style(panel).fontSize==='14px'&&style(panel).borderRadius==='12px'&&style(panel.querySelector('.activity-panel-code')).fontSize==='14px'&&style(__log).fontSize==='14px'&&style(__log).maxHeight==='100px'})()"));
  await evaluate("window.__group=turn.groups.values().next().value;__group.node.open=true;__group.manualOpen=true");
  check('running work can be expanded without replacing tool rows or local disclosure',await evaluate("__group.node.open && __log===document.querySelector('.activity-panel-output') && __json.open"));
  await evaluate("snap.items.unshift({id:'older',step:0,state:'completed',content:{kind:'tool_call',name:'read',arguments:{path:'a.md'}}});turn.update(snap)");
  check('prepending work reuses the original process group',await evaluate("turn.groups.values().next().value===__group"));
  await evaluate("__group.manualOpen=false;snap.items.forEach(i=>i.state='completed');snap.outcome={status:'completed',output:'done'};turn.update(snap)");
  check('completed work folds while the final answer remains outside the process',await evaluate("!turn.process.open && turn.answer.textContent==='done' && !turn.answer.closest('.execution-process')"));
  await evaluate("turn.setSupplemental(true)");check('additional user input prevents whole-turn hiding',await evaluate("turn.process.open"));
  await evaluate("turn.setSupplemental(false);snap.outcome={status:'failed',output:null};turn.update(snap)");check('failed execution stays inspectable rather than auto-folding the failure',await evaluate("turn.process.open && turn.summary.classList.contains('is-static')"));
  await evaluate("(async()=>{turn.dispose();document.querySelector('#timeline').replaceChildren();window.longUser=new (await import('/apps/web/run-view.mjs')).TurnView('very long '.repeat(150));document.querySelector('#timeline').append(longUser.turn);longUser.update({run_id:'finish',items:[],outcome:{status:'completed',output:'FINAL_ANSWER'}})})()");
  check('long user messages are expandable and complete answers have copy actions',await evaluate("longUser.turn.querySelector('.user-message').classList.contains('is-collapsed') && !longUser.answerActions.hidden"));
  await evaluate("document.querySelector('.conversation-find-trigger').click();const input=document.querySelector('#conversation-find input');input.value='FINAL_ANSWER';input.dispatchEvent(new Event('input',{bubbles:true}))");await pageWait("document.querySelector('.conversation-find-count').textContent.startsWith('1/1')",'conversation find');
  check('in-conversation literal search navigates an actual content match',true);
  await evaluate("renderer.renderMessage(longUser.answer,'İ hello **world** now and `hello_world`',{contextKey:'find-formatted'});{const field=document.querySelector('#conversation-find input');field.value='hello world';field.dispatchEvent(new Event('input',{bubbles:true}));}");
  await pageWait("document.querySelector('.conversation-find-count').textContent.startsWith('1/1')",'formatted search');
  check('conversation find matches across inline formatting without Unicode offset drift',await evaluate("[...CSS.highlights.get('mona-find')][0].toString()==='hello world'"));
  await evaluate("renderer.renderMessage(longUser.answer,'FINAL_ANSWER',{contextKey:'restore-answer'})");
  await evaluate("document.querySelector('#conversation-find button:last-child').click();{const selectedRange=document.createRange();selectedRange.selectNodeContents(longUser.answer.querySelector('p'));getSelection().removeAllRanges();getSelection().addRange(selectedRange);}");await pageWait("!document.querySelector('.conversation-selection').hidden",'selection actions');
  await evaluate("document.querySelector('.conversation-selection button').click()");check('selection reference fills the composer without executing a task',await evaluate("document.querySelector('#prompt').value.includes('> FINAL_ANSWER')"));
  await evaluate("getSelection().removeAllRanges();document.documentElement.dataset.theme='dark'");await screenshot('message-actions-dark');
  for(const width of [390,320]){await send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:false});await sleep(200);check(`${width}px conversation has no page-level horizontal overflow`,await evaluate(`document.documentElement.scrollWidth<=${width}`));await screenshot('conversation-'+width);}
  await evaluate("renderer.renderMessage(longUser.answer,'![local](missing.png)\\n\\n[denied](../private)',{contextKey:'errors',readMedia:()=>{throw Error('媒体没有权限')},openFile:()=>{throw Error('文件没有权限')}})");
  await evaluate("longUser.answer.querySelector('.message-file-link').click()");
  await pageWait("longUser.answer.textContent.includes('媒体没有权限') && !longUser.answer.querySelector('.message-file-link').disabled",'local authorization failure');
  check('synchronous media and file authorization errors stay in their own UI boundary',await evaluate("longUser.answer.querySelector('.message-file-link').dataset.tooltip==='文件没有权限'"));
  await evaluate("window.__reconnectCalls=0;longUser.connectionLost('连接中断但未宣称任务终止',async()=>{window.__reconnectCalls++;longUser.update({run_id:'r',items:[],outcome:{status:'completed',output:'RECONNECTED'}})});longUser.footer.querySelector('button').click()");
  await pageWait("longUser.answer.textContent==='RECONNECTED'", 'observed reconnection');
  check('connection recovery is an explicit observation action rather than an automatic task rerun',await evaluate("window.__reconnectCalls===1 && !longUser.footer.classList.contains('outcome-unknown')"));

  check('no uncaught application JavaScript errors',errors.length===0);
  await writeFile(join(output,'report.json'),JSON.stringify({passed:true,checks,errors},null,2));
}catch(error){console.error(error);console.error(errors);if(socket?.readyState===1){console.error(await evaluate("document.body.innerText.slice(-4000)").catch(()=>''));await screenshot('failure').catch(()=>{});}await writeFile(join(output,'report.json'),JSON.stringify({passed:false,checks,error:String(error),errors},null,2));process.exitCode=1;}
finally{if(socket?.readyState===1){await send('Browser.close').catch(()=>{});socket.close();}for(const item of pending.values())clearTimeout(item.timer);if(browser?.exitCode==null){browser.kill('SIGKILL');await sleep(400);}ui?.closeAllConnections();api?.closeAllConnections();if(ui)await new Promise(r=>ui.close(r));if(api)await new Promise(r=>api.close(r));await rm(scratch,{recursive:true,force:true,maxRetries:5,retryDelay:100}).catch(()=>{});}
