// Real Rust host and Web, SDK transports and real stdio peer; model remains controlled.
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { mkdtemp,mkdir,readFile,writeFile,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join,resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { startUiServer } from '../../../scripts/dev-web.mjs';
import { startHttpFixture } from '../../../packages/mcp/tests/fixture.mjs';
const root=fileURLToPath(new URL('../../../',import.meta.url));
const scratch=await mkdtemp(join(tmpdir(),'mona-mcp-')),state=join(scratch,'state'),home=join(scratch,'home');
for(const p of [state,home])await mkdir(p,{recursive:true});
const report=join(root,'target/mcp-validation/browser');await mkdir(report,{recursive:true});
const token='mcp-browser-isolated-bearer-at-least-32-characters',secret='MCP_TEST_HEADER_VALUE',checks=[],errors=[],requests=[],results=new Map();
let host,ui,browser,socket,hostLog='',sequence=0;const pending=new Map();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function wait(fn,label,timeout=40000){const end=Date.now()+timeout;while(Date.now()<end){if(await fn())return;await sleep(75);}throw Error('Timeout: '+label);}
function check(name,ok){assert.ok(ok,name);checks.push(name);console.log('PASS '+name);}
async function freePort(){const s=createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const p=s.address().port;await new Promise(r=>s.close(r));return p;}
async function stop(child){if(!child||child.exitCode!=null)return;const exit=once(child,'exit');child.kill('SIGKILL');await Promise.race([exit,sleep(5000)]);}
const http=await startHttpFixture({auth:secret});
const tasks={ECHO_HTTP:['mcp__remote__echo',{message:'HTTP_OK'}],ECHO_STDIO:['mcp__local__echo',{message:'STDIO_OK'}],BAD_ARGS:['mcp__remote__echo',{message:17}],REMOTE_FAIL:['mcp__remote__fail',{message:'fail'}],READ_RESOURCE:['mcp_read_resource',{server:'remote',uri:'fixture://http/readme'}],READONLY_DENY:['mcp__remote__echo',{message:'not allowed'}],SLOW_CANCEL:['mcp__remote__slow',{message:'wait'}],PLAN_READ:['mcp__local__echo',{message:'plan-read'}]};
const model=createServer(async(req,res)=>{try{
 let raw='';for await(const c of req){raw+=c;if(raw.length>4*1024*1024)throw Error('model fixture bound');}const body=JSON.parse(raw);requests.push(body);
 const index=body.messages.findLastIndex(m=>m.role==='user'&&typeof m.content==='string'&&!m.content.startsWith('[Host context source:'));
 const prompt=body.messages[index]?.content,tail=body.messages.slice(index+1),out=tail.find(m=>m.role==='tool');
 res.writeHead(200,{'Content-Type':'text/event-stream'});const frame=v=>res.write(`data: ${JSON.stringify(v)}\n\n`);
 if(tasks[prompt]&&!out){const[name,args]=tasks[prompt];assert.ok(body.tools.some(t=>t.function.name===name),name+' should be offered');frame({choices:[{index:0,delta:{tool_calls:[{index:0,id:'mcp-call-'+requests.length,type:'function',function:{name,arguments:JSON.stringify(args)}}]},finish_reason:'tool_calls'}]});}
 else{if(out)results.set(prompt,JSON.parse(out.content));frame({choices:[{index:0,delta:{content:'FINISHED '+prompt},finish_reason:'stop'}]});}
 frame({choices:[],usage:{prompt_tokens:100,completion_tokens:10}});res.end('data: [DONE]\n\n');
}catch(e){errors.push(String(e));res.destroy();}});await new Promise(r=>model.listen(0,'127.0.0.1',r));
const port=await freePort(),endpoint=`http://127.0.0.1:${port}`;
async function api(path,body,expected=200,authorized=true){const r=await fetch(endpoint+path,{method:body==null?'GET':'POST',headers:{...(authorized?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json'},body:body==null?undefined:JSON.stringify(body),signal:AbortSignal.timeout(35000)});const text=await r.text();assert.equal(r.status,expected,`${path}: ${text}`);return text?JSON.parse(text):null;}
async function start(origin,extra={}){
 const env=Object.fromEntries(Object.entries(process.env).filter(([k])=>!k.startsWith('AGENT_')&&!k.startsWith('MONA_DEV_')));
 Object.assign(env,{MONA_DEV_STATE_DIR:state,HOME:home,USERPROFILE:home,AGENT_SERVER_ADDR:`127.0.0.1:${port}`,AGENT_SERVER_TOKEN:token,AGENT_UI_ORIGIN:origin,AGENT_MODEL_MANAGEMENT:'0',AGENT_MODEL_NAME:'mcp-fixture',AGENT_MODEL_ENDPOINT:`http://127.0.0.1:${model.address().port}/v1/chat/completions`,AGENT_MODEL_KEY:'PRIVATE_PARENT_KEY',AGENT_ALLOW_HTTP_LOOPBACK:'1',AGENT_MCP_SETTINGS_PATH:join(state,'mcp.enc'),AGENT_CAPABILITY_STATE_PATH:join(state,'capabilities.json'),AGENT_INSTRUCTIONS:'0',AGENT_COMPACTION:'0',AGENT_SPILL:'0',...extra});
 hostLog='';host=spawn(resolve(process.env.MONA_TEST_SERVER||join(root,'target/debug',process.platform==='win32'?'server.exe':'server')),[],{cwd:scratch,env,stdio:['ignore','pipe','pipe']});host.stderr.on('data',c=>hostLog=(hostLog+c).slice(-20000));host.on('error',e=>errors.push(String(e)));
 await wait(async()=>{if(host.exitCode!=null)throw Error(hostLog);try{return(await api('/v1/info')).protocol_version===2;}catch{return false;}},'host ready',65000);
}
function cdp(method,params={}){return new Promise((resolve,reject)=>{const id=++sequence,timer=setTimeout(()=>{pending.delete(id);reject(Error('CDP '+method));},20000);pending.set(id,{resolve,reject,timer});socket.send(JSON.stringify({id,method,params}));});}
async function evaluate(expression){const r=await cdp('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||'browser exception');return r.result.value;}
const pageWait=(e,l)=>wait(()=>evaluate(e),l);
async function click(selector){const p=await evaluate(`(()=>{const n=document.querySelector(${JSON.stringify(selector)});if(!n||n.disabled)throw Error('unavailable '+${JSON.stringify(selector)});n.scrollIntoView({block:'nearest'});const r=n.getBoundingClientRect();if(!r.width||!r.height)throw Error('hidden '+${JSON.stringify(selector)});return{x:r.x+r.width/2,y:r.y+r.height/2};})()`);await cdp('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...p});await cdp('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...p});}
async function fill(selector,value){await evaluate(`(()=>{const n=document.querySelector(${JSON.stringify(selector)});if(n.type==='checkbox')n.checked=${JSON.stringify(value)};else n.value=${JSON.stringify(value)};n.dispatchEvent(new Event('input',{bubbles:true}));n.dispatchEvent(new Event('change',{bubbles:true}));})()`);}
async function shot(name){const r=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(join(report,name+'.png'),Buffer.from(r.data,'base64'));}
async function settings(){await click('#settings-button');await click('#settings-mcp-tab');await pageWait("!document.querySelector('#mcp-add').disabled",'MCP settings');}
let session;
async function begin(prompt){await pageWait("!document.querySelector('#prompt').disabled&&!document.querySelector('#sessions-refresh').disabled",'composer');await fill('#prompt',prompt);await pageWait("!document.querySelector('#send').disabled",'send');await click('#send');await pageWait("/^#session=/.test(location.hash)",'session selected');session=await evaluate("location.hash.slice(9)");}
async function task(prompt){const count=session?(await api('/api/sessions/'+session)).session.turn_count:0;await begin(prompt);await wait(async()=>{const d=await api('/api/sessions/'+session);if(d.session.status==='failed')throw Error(JSON.stringify(d));return d.session.turn_count>count&&d.session.status==='completed';},prompt);await pageWait("document.querySelector('#cancel').hidden&&!document.querySelector('#sessions-refresh').disabled",'settled');}
try{
 ui=await startUiServer({host:'127.0.0.1',port:0,endpoint,token});const origin=`http://127.0.0.1:${ui.address().port}`;await start(origin);
 await api('/api/mcp',null,401,false);check('unconfigured MCP adds no external tools and reports actual empty state',(await api('/api/mcp')).servers.length===0);
 const debug=await freePort();browser=spawn(process.env.BROWSER_BIN||(process.platform==='win32'?'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe':'chromium'),['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check',`--remote-debugging-port=${debug}`,`--user-data-dir=${join(scratch,'browser')}`,'about:blank'],{stdio:'ignore'});
 let page;await wait(async()=>{try{page=(await(await fetch(`http://127.0.0.1:${debug}/json/list`)).json()).find(p=>p.type==='page');return!!page;}catch{return false;}},'browser');socket=new WebSocket(page.webSocketDebuggerUrl);await once(socket,'open');socket.addEventListener('message',e=>{const m=JSON.parse(e.data),p=pending.get(m.id);if(p){pending.delete(m.id);clearTimeout(p.timer);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||'browser exception');});
 await cdp('Page.enable');await cdp('Runtime.enable');await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await cdp('Page.navigate',{url:origin});await pageWait("document.querySelector('#settings-mcp-tab')&&!document.querySelector('#prompt').disabled",'module mounted');await settings();
 await click('#mcp-add');await fill('#mcp-id','local');await fill('#mcp-command',process.execPath);await fill('#mcp-args',JSON.stringify([join(root,'packages/mcp/tests/fixture.mjs')]));await fill('#mcp-cwd',scratch);await fill('#mcp-env',JSON.stringify({MCP_FIXTURE_KEY:'LOCAL_TEST_SECRET',MCP_FIXTURE_LOG:join(scratch,'stdio.log')}));await fill('#mcp-enabled',true);await fill('#mcp-read-only-tools','["echo"]');await click('#mcp-save');await pageWait("document.querySelector('#mcp-entry-local')&&!document.querySelector('#mcp-save').disabled",'local saved');
 check('saving stdio configuration is real but does not start a process before restart',(await api('/api/mcp')).restart_required&&!(await api('/api/mcp')).status.length);
 check('saved environment values are removed from the form and management response',await evaluate("document.querySelector('#mcp-env').value===''")&&!JSON.stringify(await api('/api/mcp')).includes('LOCAL_TEST_SECRET'));
 await click('#mcp-add');await fill('#mcp-id','remote');await fill('#mcp-transport','streamable-http');await fill('#mcp-url',http.url);await fill('#mcp-headers',JSON.stringify({'x-mcp-key':secret}));await fill('#mcp-enabled',true);await click('#mcp-save');await pageWait("document.querySelector('#mcp-entry-remote')&&!document.querySelector('#mcp-save').disabled",'remote saved');
 check('secrets are encrypted at rest and not returned to the page',!(await readFile(join(state,'mcp.enc'))).includes(Buffer.from(secret))&&!JSON.stringify(await api('/api/mcp')).includes(secret));
 const saved=await api('/api/mcp');await api('/api/mcp/delete',{revision:0,id:'remote'},409);check('stale settings writes preserve the current saved revision',(await api('/api/mcp')).revision===saved.revision);
 await shot('mcp-settings-pending');await stop(host);await start(origin);const ready=await api('/api/mcp');check('both official SDK transports initialize, paginate and restore saved credentials after restart',ready.status.length===2&&ready.status.every(s=>s.connected&&s.tools.length===6)&&!ready.restart_required);
 await cdp('Page.reload',{ignoreCache:true});await pageWait("document.querySelector('#settings-mcp-tab')&&!document.querySelector('#prompt').disabled",'module remounted');await task('ECHO_HTTP');check('model calls the real Streamable HTTP tool once',results.get('ECHO_HTTP').status==='success'&&http.calls.filter(c=>c.args.message==='HTTP_OK').length===1);
 await task('ECHO_STDIO');check('stdio does not inherit parent credentials but receives explicit host environment',results.get('ECHO_STDIO').content.includes('host-secret=false:explicit-secret=true'));
 const before=http.calls.length;await task('BAD_ARGS');check('central JSON Schema validation rejects bad fields before sending MCP',results.get('BAD_ARGS').status==='error'&&http.calls.length===before);
 await task('REMOTE_FAIL');check('MCP isError remains a tool error rather than false success',results.get('REMOTE_FAIL').status==='error'&&results.get('REMOTE_FAIL').content.includes('REMOTE_TOOL_ERROR'));
 await task('READ_RESOURCE');check('MCP resources are fetched only through an explicit tool',results.get('READ_RESOURCE').content.includes('RESOURCE_http'));
 check('attributed server instructions enter model context without granting permissions',requests.some(r=>r.messages.some(m=>String(m.content).includes('mcp.remote.instructions')&&String(m.content).includes('REFERENCE_FROM_http'))));
 await click('#composer-add');await click('[data-command="plan"]');await pageWait("!document.querySelector('#planner-mode-chip').hidden&&!document.querySelector('#planner-mode-chip').disabled",'plan mode');await task('PLAN_READ');check('Planner uses only MCP tools explicitly confirmed read-only by the host',results.get('PLAN_READ').status==='success');await click('#planner-mode-chip');await pageWait("document.querySelector('#planner-mode-chip').hidden",'exit plan');
 await click('#sandbox-permission');await click('[data-sandbox-mode="read-only"]');await pageWait("document.querySelector('#sandbox-permission .permission-trigger-label').textContent==='仅可查看'&&!document.querySelector('#sandbox-permission').disabled",'read-only confirmed');const calls=http.calls.length;await task('READONLY_DENY');check('read-only policy denies untrusted MCP side effects before dispatch',results.get('READONLY_DENY').status==='denied'&&http.calls.length===calls);
 await click('#sandbox-permission');await click('[data-sandbox-mode="workspace-write"]');await pageWait("document.querySelector('#sandbox-permission .permission-trigger-label').textContent==='工作区内修改'&&!document.querySelector('#sandbox-permission').disabled",'workspace-write confirmed');await begin('SLOW_CANCEL');await wait(()=>http.calls.some(c=>c.name==='slow'),'slow remote call');await click('#cancel');await wait(()=>http.cancelled.length>0,'MCP cancellation notification');await wait(async()=>(await api('/api/sessions/'+session)).session.status==='cancelled','cancelled task');check('cancellation is forwarded and the remote invocation is not replayed',http.calls.filter(c=>c.name==='slow').length===1);
 await pageWait("!document.querySelector('#sessions-refresh').disabled",'cancel settled');await settings();await click('#mcp-entry-remote');await shot('mcp-settings-light');
 await click('#mcp-reconnect');await pageWait("!document.querySelector('#mcp-reconnect').disabled",'reconnect settled');check('explicit reconnect retains the same tool identities',(await api('/api/mcp')).status.find(s=>s.id==='remote').connected);
 await evaluate("(async()=>{const {browserTheme}=await import('/apps/web/theme.mjs');browserTheme.update({mode:'dark'});})()");await shot('mcp-settings-dark');
 for(const width of [390,320]){await cdp('Emulation.setDeviceMetricsOverride',{width,height:950,deviceScaleFactor:1,mobile:true});check(`MCP settings fit ${width}px`,await evaluate('document.documentElement.scrollWidth<=innerWidth+1'));await shot('mcp-'+width);}
 await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await stop(host);await start(origin,{AGENT_MCP:'0'});const disabled=await api('/api/mcp');check('disabled extension preserves configuration without connecting external processes',!disabled.enabled&&disabled.servers.length===2&&disabled.status.length===0);
 check('no unhandled browser or model fixture errors',errors.length===0);await writeFile(join(report,'result.json'),JSON.stringify({passed:true,checks,real_provider:false,isolated:true,model_calls:requests.length},null,2));
}catch(e){console.error(e);console.error(hostLog);if(socket?.readyState===1){console.error(await evaluate('document.body.innerText.slice(-4000)').catch(()=>''));await shot('failure').catch(()=>{});}await writeFile(join(report,'result.json'),JSON.stringify({passed:false,checks,error:String(e),errors},null,2));process.exitCode=1;}
finally{if(socket?.readyState===1){await cdp('Browser.close').catch(()=>{});socket.close();}for(const p of pending.values())clearTimeout(p.timer);await stop(browser);await stop(host);ui?.closeAllConnections();model.closeAllConnections();if(ui)await new Promise(r=>ui.close(r));await new Promise(r=>model.close(r));await http.close();await rm(scratch,{recursive:true,force:true,maxRetries:8,retryDelay:200});}
